# Generated by Django 3.1.7 on 2021-08-21 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.PositiveIntegerField(null=True)),
                ('teacherId', models.PositiveIntegerField(null=True)),
                ('studentName', models.CharField(max_length=40, null=True)),
                ('teacherName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/TeacherProfilePic/')),
                ('position', models.CharField(choices=[('Position', 'Position'), ('Teacher1', 'Teacher1'), ('Teacher2', 'Teacher2'), ('Teacher3', 'Teacher3'), ('Teacher4', 'Teacher4')], default='Position', max_length=50)),
                ('department', models.CharField(choices=[('Department', 'Department'), ('Industrial Education', 'Industrial Education'), ('ITDept', 'ITDept'), ('Math and Science', 'Math and Science')], default='Department', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/StudentProfilePic/')),
                ('course', models.CharField(choices=[('Select Course', 'Select Course'), ('BSIE-ICT', 'BSIE-ICT'), ('BSIE-IA', 'BSIE-IA'), ('CIVIL ENGENEERING', 'CIVIL ENGENEERING'), ('COET', 'COET'), ('BET ESET', 'BET ESET'), ('ELECTRICAL ENGENEERING', 'ELECTRICAL ENGENEERING'), ('MECHANICAL ENGENEERING', 'MECHANICAL ENGENEERING')], default='Select Course', max_length=50)),
                ('year', models.CharField(choices=[('Select Year', 'Select Year'), ('1st year', '1st year'), ('2nd year', '2nd year'), ('3rd year', '3rd year'), ('4th year', '4th year')], default='Select Year', max_length=50)),
                ('violation', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100, null=True)),
                ('scheduleday', models.CharField(max_length=100, null=True)),
                ('hoursperday', models.CharField(max_length=100, null=True)),
                ('assignedTeacherId', models.PositiveIntegerField(null=True)),
                ('admitDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
